# docker stop chaincuet_wiki && docker rm chaincuet_wiki && docker rmi chaincuet_wiki
# docker build -t chaincuet_wiki .
# docker-compose up
# docker exec -it chaincuet_wiki sh

# docker stop chaincuet_wiki && docker rm chaincuet_wiki && docker rmi chaincuet_wiki && docker build -t chaincuet_wiki . && docker-compose up
version: '3.7'

services:
  chaincuet_wiki:
    container_name: chaincuet_wiki
    image: chaincuet_wiki:latest
    ports:
      - "8000:80"
    networks:
      - keycloak_net

networks:
  keycloak_net:
    name: keycloak_net
    driver: bridge
