site_name: Chaincue Technologies Docs
repo_url: https://github.com/KQT3/chaincuet-wiki
use_directory_urls: true
#extra_css:
#  - stylesheets/extra.css
#extra_javascript:
#  - javascripts/extra.js
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://chaincuet.com/
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

theme:
  name: material
  custom_dir: overrides
  logo: assets/static/favicon.ico
  favicon: assets/static/favicon.ico
  palette:
    scheme: default
    primary: blue grey
    accent: deep purple
  features:
    - navigation.tabs
    - header.autohide
  include_sidebar: true

nav:
  - Welcome:
      - "": index.md
  - AWS:
      - AWS Overview: aws/index.md
      - S3 & Cloudfront: aws/s3-cloudfront.md
      - Route53: aws/route53.md
      - Aws Lambda: aws/aws-lambda.md
      - Vault: aws/vault.md
  - Docker & Kubernetes:
      - Overview: docker-kubernetes/index.md
      - Docker: docker-kubernetes/docker.md
      - Kubernetes: docker-kubernetes/kubernetes.md
      - Deploy K8s: docker-kubernetes/deployment-k8s.md
  - Spring Cloud Architecture:
      - Spring Cloud Overview: spring-cloud-architecture/index.md
      - Domains: spring-cloud-architecture/domains.md
      - Services: spring-cloud-architecture/services.md
      - Tracing: spring-cloud-architecture/tracing.md
  - Frontend:
      - Frontend Overview: frontend/index.md
      - Style: frontend/style.md
      - Javascript & Typescript: frontend/javascript-typescript.md
  - Linux:
      - Linux Overview: linux/index.md
      - Alias: linux/alias.md
  - Utils: 
      - Utils Overview: utils/index.md
      - Emoji: utils/emoji.md
      - Git: utils/git.md
