site_name: Chancue Technologies Docs
repo_url: https://github.com/KQT3/chaincuet-wiki
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.footer
  include_sidebar: true
plugins:
  - search:
      lang: en
  - tags

nav:
  - Welcome:
      - Docs: index.md
  - AWS:
      - Welcome: aws/index.md
      - Cloudfront: aws/cloudfront.md
      - Route53: aws/route53.md
      - S3: aws/s3.md
  - Kubernetes:
      - Kubernetes: kubernetes/index.md
      - Deployment: kubernetes/deployment.md
  - Spring Cloud Architecture:
      - Spring Cloud Overview: spring-cloud-architecture/index.md
      - Domains: spring-cloud-architecture/domains.md
      - Services: spring-cloud-architecture/services.md
      - Tracing: spring-cloud-architecture/tracing.md



