site_name: Chancue Technologies Docs
repo_url: https://github.com/KQT3/chaincuet-wiki
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
use_directory_urls: true

theme:
  name: material
  logo: assets/static/favicon.ico
  favicon: assets/static/favicon.ico
  palette:
    scheme: default
    primary: blue grey
    accent: deep purple
  custom_dir: overrides
  features:
    - navigation.tabs
    - header.autohide
  include_sidebar: true
extra:
    social:
    - icon: fontawesome/solid/house
      link: https://chaincuet.com/
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

nav:
  - Welcome: index.md
  - AWS:
      - AWS Overview: aws/index.md
      - S3 & Cloudfront: aws/s3-cloudfront.md
      - Route53: aws/route53.md
      - Aws Lambda: aws/aws-lambda.md
  - Docker & Kubernetes:
      - Overview: docker-kubernetes/index.md
      - Docker: docker-kubernetes/docker.md
      - Kubernetes: docker-kubernetes/deployment-k8s.md
  - Spring Cloud Architecture:
      - Spring Cloud Overview: spring-cloud-architecture/index.md
      - Domains: spring-cloud-architecture/domains.md
      - Services: spring-cloud-architecture/services.md
      - Tracing: spring-cloud-architecture/tracing.md



