site_name: Chaincue Technologies Docs
repo_url: https://github.com/KQT3/chaincuet-wiki
use_directory_urls: true
#extra_css:
#  - stylesheets/extra.css
#extra_javascript:
#  - javascripts/extra.js
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://chaincuet.com/
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

theme:
  name: material
  custom_dir: overrides
  logo: assets/static/favicon.ico
  favicon: assets/static/favicon.ico
  palette:
    scheme: default
    primary: blue grey
    accent: deep purple
  features:
    - navigation.tabs
    - header.autohide
  include_sidebar: true

nav:
  - Welcome:
      - "": index.md
  - AWS / Devopss:
      - AWS Overview: aws/index.md
      - S3 & Cloudfront: aws/s3-cloudfront.md
      - Route53: aws/route53.md
      - AWS Lambda & API Gateway: aws/aws-lambda-api-gateway.md
      - ECS/ECR: aws/ecs.md
      - Terraform: aws/terraform.md
      - VPN: aws/vpn.md
      - Nginx: aws/nginx.md
      - Vault: aws/vault.md
      - Keycloak: aws/keycloak.md
  - Docker & Kubernetes:
      - Overview: docker-kubernetes/index.md
      - Docker: docker-kubernetes/docker.md
      - Kubernetes Commands: docker-kubernetes/kubernetes-commands.md
      - Kubernetes Production: docker-kubernetes/kubernetes-production.md
  - Spring Cloud Architecture:
      - Spring Cloud Overview: spring-cloud-architecture/index.md
      - Domains: spring-cloud-architecture/domains.md
      - Services: spring-cloud-architecture/services.md
      - Tracing: spring-cloud-architecture/tracing.md
  - Frontend:
      - Frontend Overview: frontend/index.md
      - HTML: frontend/html.md
      - CSS Styling: frontend/css-styling.md
      - Javascript & Typescript: frontend/javascript-typescript.md
      - Gists: frontend/gists.md
  - AI:
      - Artificial intelligence: ai/index.md
      - OpenAI: ai/openAI.md
  - Linux:
      - Linux Overview: linux/index.md
      - Alias: linux/alias.md
  - Utils: 
      - Utils Overview: utils/index.md
      - Emoji: utils/emoji.md
      - Git: utils/git.md
